language: java
sudo: true
dist: trusty
jdk: oraclejdk9
services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
    - oracle-java9-installer
before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -ppassword
- sudo service mysql restart
- chmod +x mvnw
- mysql -u root -p password
  CREATE DATABASE IF NOT EXISTS test;
  CREATE TABLE IF NOT EXISTS SKROTY(SKROT VARCHAR(255) UNIQUE NOT NULL, ROZWINIECIE VARCHAR(255) NOT NULL);
  exit
install: mvn clean install -P-quality-checks -DskipTests
script:
- mvn install
notifications:
  email:
    on_success: always
    on_failure: always