language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
    - oracle-java9-installer
before_install:
- chmod +x mvnw
install: mvn clean install -P-quality-checks -DskipTests
script:
- mvn install
notifications:
  email:
    on_success: always
    on_failure: always